"""Employer intelligence — job distribution, departments, pipelines, compliance, events.

Closes gaps: #106-#115 (offers/onboarding extras), #116-#130 (employer features).
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime

# ---------------------------------------------------------------------------
# Gap #106: Offer letter HTML for PDF
# ---------------------------------------------------------------------------

def generate_offer_html(offer: dict) -> str:
    """Generate print-ready HTML for an offer letter."""
    from html import escape
    title = escape(str(offer.get("role_title", "")))
    comp = escape(str(offer.get("compensation_text", "Competitive")))
    start = offer.get("start_date", "TBD")
    conditions = offer.get("conditions", [])
    cond_items = "".join(f"<li>{escape(str(c))}</li>" for c in conditions)

    return f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Offer Letter — {title}</title>
<style>body{{font-family:system-ui;max-width:700px;margin:40px auto;padding:0 20px}}
h1{{border-bottom:2px solid #3b82f6;padding-bottom:8px}} .meta{{color:#6b7280;font-size:14px}}</style>
</head><body><h1>Offer of Employment</h1>
<p><strong>Position:</strong> {title}</p>
<p><strong>Compensation:</strong> {comp}</p>
<p><strong>Start Date:</strong> {escape(str(start))}</p>
{"<h3>Conditions</h3><ul>" + cond_items + "</ul>" if conditions else ""}
<p class="meta">Generated by OpenSkill Studio — {datetime.now(UTC).strftime('%Y-%m-%d')}</p>
</body></html>"""


# ---------------------------------------------------------------------------
# Gap #108: Offer comparison
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class OfferComparison:
    offers: list[dict]
    best_compensation: str | None
    earliest_start: str | None
    fewest_conditions: int


def compare_offers(offers: list[dict]) -> OfferComparison:
    """Compare multiple offers side by side."""
    if not offers:
        return OfferComparison([], None, None, 0)
    best_comp = max(offers, key=lambda o: len(o.get("compensation_text", "")))
    earliest = min(offers, key=lambda o: o.get("start_date", "9999"))
    fewest = min(len(o.get("conditions", [])) for o in offers)
    return OfferComparison(
        offers=offers,
        best_compensation=best_comp.get("role_title"),
        earliest_start=earliest.get("start_date"),
        fewest_conditions=fewest,
    )


# ---------------------------------------------------------------------------
# Gap #109: Offer deadline reminder
# ---------------------------------------------------------------------------

def compute_offer_deadline_alerts(offers: list[dict], days_ahead: int = 3) -> list[dict]:
    """Find offers expiring within N days."""
    now = datetime.now(UTC)
    alerts = []
    for o in offers:
        exp = o.get("expires_at")
        if not exp:
            continue
        if isinstance(exp, str):
            try:
                from datetime import datetime as dt
                exp = dt.fromisoformat(exp)
            except (ValueError, TypeError):
                continue
        from datetime import timedelta
        if now < exp <= now + timedelta(days=days_ahead):
            alerts.append({
                "offer_id": o.get("id"),
                "role_title": o.get("role_title"),
                "expires_at": exp.isoformat(),
                "hours_remaining": round((exp - now).total_seconds() / 3600, 1),
            })
    return alerts


# ---------------------------------------------------------------------------
# Gap #118: Department hierarchy
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class Department:
    id: str
    org_id: str
    name: str
    parent_department_id: str | None
    head_user_id: str | None
    member_count: int


def build_department_tree(departments: list[dict]) -> list[dict]:
    """Build hierarchical department tree from flat list."""
    by_id = {d["id"]: {**d, "children": []} for d in departments}
    roots = []
    for d in by_id.values():
        parent = d.get("parent_department_id")
        if parent and parent in by_id:
            by_id[parent]["children"].append(d)
        else:
            roots.append(d)
    return roots


# ---------------------------------------------------------------------------
# Gap #121: Custom pipeline stages
# ---------------------------------------------------------------------------

DEFAULT_PIPELINE_STAGES = [
    "submitted", "screening", "interview", "assessment", "offer",
    "accepted", "rejected", "withdrawn", "hired", "completed",
]

CUSTOMIZABLE_STAGES = [
    "phone_screen", "technical_interview", "culture_fit",
    "panel_interview", "reference_check", "background_check",
    "negotiation", "onboarding_prep",
]


def validate_custom_pipeline(stages: list[str]) -> list[str]:
    """Validate a custom pipeline configuration."""
    errors = []
    if "submitted" not in stages:
        errors.append("Pipeline must include 'submitted' as first stage")
    if "hired" not in stages and "completed" not in stages:
        errors.append("Pipeline must include a terminal stage (hired/completed)")
    if len(stages) < 3:
        errors.append("Pipeline must have at least 3 stages")
    if len(stages) > 15:
        errors.append("Pipeline must not exceed 15 stages")
    if len(set(stages)) != len(stages):
        errors.append("Duplicate stages not allowed")
    return errors


# ---------------------------------------------------------------------------
# Gap #122: Talent pool rule evaluation
# ---------------------------------------------------------------------------

POOL_RULE_TYPES = frozenset({
    "min_capability_level", "has_credential", "min_endorsements",
    "min_evidence_count", "capability_category", "availability_status",
})


def evaluate_pool_rule(rule: dict, candidate: dict) -> bool:
    """Evaluate a single pool rule against candidate data."""
    rt = rule.get("rule_type", "")
    value = rule.get("value")
    field = rule.get("field", rt)
    candidate_val = candidate.get(field)

    if rt == "min_capability_level":
        return (candidate_val or 0) >= (value or 0)
    if rt == "has_credential":
        creds = candidate.get("credential_types", [])
        return value in creds
    if rt == "min_endorsements":
        return (candidate_val or 0) >= (value or 0)
    if rt == "min_evidence_count":
        return (candidate_val or 0) >= (value or 0)
    if rt == "availability_status":
        return candidate.get("availability_status") == value
    return False


def evaluate_pool_rules(rules: list[dict], candidate: dict) -> dict:
    """Evaluate all pool rules. Returns {eligible, matched, total}."""
    if not rules:
        return {"eligible": True, "matched": 0, "total": 0}
    matched = sum(1 for r in rules if evaluate_pool_rule(r, candidate))
    return {"eligible": matched == len(rules), "matched": matched, "total": len(rules)}


# ---------------------------------------------------------------------------
# Gap #124: Interview preparation kit
# ---------------------------------------------------------------------------

INTERVIEW_KIT_SECTIONS = [
    "role_overview", "required_capabilities", "interview_questions",
    "evaluation_criteria", "scoring_rubric", "logistics",
]


def generate_interview_kit(opportunity: dict, stage_type: str) -> dict:
    """Generate an interview preparation kit for interviewers."""
    from html import escape
    return {
        "role_title": escape(str(opportunity.get("title", ""))),
        "opportunity_type": opportunity.get("opportunity_type", ""),
        "required_capabilities": opportunity.get("required_capabilities", []),
        "preferred_capabilities": opportunity.get("preferred_capabilities", []),
        "stage_type": stage_type,
        "suggested_questions": _get_stage_questions(stage_type),
        "evaluation_tips": _get_evaluation_tips(stage_type),
        "sections": INTERVIEW_KIT_SECTIONS,
    }


def _get_stage_questions(stage_type: str) -> list[str]:
    questions = {
        "technical": [
            "Walk me through a recent technical challenge you solved",
            "How do you approach debugging complex issues?",
            "Describe your experience with [relevant technology]",
        ],
        "behavioral": [
            "Tell me about a time you handled a disagreement with a colleague",
            "Describe a project where you had to learn something new quickly",
            "How do you prioritize when facing multiple deadlines?",
        ],
        "portfolio": [
            "Walk me through your favorite project in your portfolio",
            "What was the most challenging aspect of this work?",
            "How did you handle client feedback on this deliverable?",
        ],
    }
    return questions.get(stage_type, questions.get("behavioral", []))


def _get_evaluation_tips(stage_type: str) -> list[str]:
    return [
        "Focus on demonstrated capability, not credentials alone",
        "Note specific examples and evidence cited",
        "Assess problem-solving approach, not just answers",
        "Consider culture fit alongside technical skills",
    ]


# ---------------------------------------------------------------------------
# Gap #125: Compliance reporting
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class ComplianceReport:
    report_type: str
    period_start: str
    period_end: str
    total_applications: int
    applications_by_source: dict[str, int]
    applications_by_stage: dict[str, int]
    offer_rate: float
    hire_rate: float
    adverse_impact_flags: list[str]


def compute_adverse_impact(
    group_a_selected: int, group_a_total: int,
    group_b_selected: int, group_b_total: int,
) -> dict:
    """Compute adverse impact ratio (four-fifths rule).

    If selection rate for any group < 80% of highest group → adverse impact.
    """
    rate_a = group_a_selected / group_a_total if group_a_total > 0 else 0
    rate_b = group_b_selected / group_b_total if group_b_total > 0 else 0

    if rate_a == 0 and rate_b == 0:
        return {"ratio": 1.0, "adverse_impact": False, "note": "No selections"}

    higher = max(rate_a, rate_b)
    lower = min(rate_a, rate_b)
    ratio = lower / higher if higher > 0 else 0

    return {
        "ratio": round(ratio, 3),
        "adverse_impact": ratio < 0.8,
        "threshold": 0.8,
        "rate_a": round(rate_a, 3),
        "rate_b": round(rate_b, 3),
    }


# ---------------------------------------------------------------------------
# Gap #126: Candidate relationship timeline
# ---------------------------------------------------------------------------

def build_relationship_timeline(events: list[dict]) -> list[dict]:
    """Build a unified timeline of all interactions with a candidate.

    Merges: applications, messages, interviews, outreach, notes.
    """
    timeline = []
    for ev in events:
        timeline.append({
            "type": ev.get("type", "unknown"),
            "timestamp": ev.get("timestamp"),
            "summary": ev.get("summary", ""),
            "actor": ev.get("actor"),
            "details": ev.get("details"),
        })
    timeline.sort(key=lambda e: e.get("timestamp", ""))
    return timeline


# ---------------------------------------------------------------------------
# Gap #128: Requisition approval
# ---------------------------------------------------------------------------

APPROVAL_STATUSES = frozenset({"draft", "pending_approval", "approved", "rejected"})


def validate_requisition(req: dict) -> list[str]:
    """Validate a job requisition for approval."""
    errors = []
    if not req.get("title"):
        errors.append("Job title is required")
    if not req.get("department"):
        errors.append("Department is required")
    if not req.get("justification") or len(req.get("justification", "")) < 20:
        errors.append("Business justification must be at least 20 characters")
    if req.get("headcount", 0) < 1:
        errors.append("Headcount must be at least 1")
    return errors


# ---------------------------------------------------------------------------
# Gap #129: Brand health metrics
# ---------------------------------------------------------------------------

def compute_brand_health_trend(snapshots: list[dict]) -> dict:
    """Compute employer brand health trend over time."""
    if not snapshots:
        return {"trend": "insufficient_data", "snapshots": []}

    scores = [s.get("reputation_score", 0) for s in snapshots]
    if len(scores) < 2:
        return {"trend": "insufficient_data", "current": scores[0] if scores else 0, "snapshots": snapshots}

    recent = scores[-1]
    previous = scores[-2]
    delta = recent - previous

    if delta > 5:
        trend = "improving"
    elif delta < -5:
        trend = "declining"
    else:
        trend = "stable"

    return {
        "trend": trend,
        "current": recent,
        "previous": previous,
        "delta": round(delta, 1),
        "snapshots": snapshots,
    }
