from fastapi import APIRouter

from app.api.v1.endpoints import (
    admin,
    auth,
    certificates,
    client_briefs,
    cohorts,
    discussions,
    duplicate,
    evaluation,
    gamification,
    health,
    installations,
    learning_paths,
    lti,
    notifications,
    organizations,
    overview,
    pack_io,
    pack_reviews,
    pack_sharing,
    peer_review,
    portfolio,
    projects,
    providers,
    registry,
    skill_packs,
    skills,
    webhooks,
    workflow_packs,
    workflow_runs,
)

api_v1_router = APIRouter()
api_v1_router.include_router(health.router)
api_v1_router.include_router(auth.router)
api_v1_router.include_router(admin.router)
api_v1_router.include_router(organizations.router)
api_v1_router.include_router(skills.router)
api_v1_router.include_router(projects.router)
api_v1_router.include_router(peer_review.router)
api_v1_router.include_router(overview.router)
api_v1_router.include_router(evaluation.router)
api_v1_router.include_router(cohorts.router)
api_v1_router.include_router(client_briefs.router)
api_v1_router.include_router(portfolio.router)
api_v1_router.include_router(skill_packs.router)
api_v1_router.include_router(registry.router)
api_v1_router.include_router(pack_reviews.router)
api_v1_router.include_router(installations.router)
api_v1_router.include_router(learning_paths.router)
api_v1_router.include_router(pack_io.router)
api_v1_router.include_router(notifications.router)
api_v1_router.include_router(certificates.router)
api_v1_router.include_router(lti.router)
api_v1_router.include_router(webhooks.router)
api_v1_router.include_router(discussions.router)
api_v1_router.include_router(gamification.router)
api_v1_router.include_router(duplicate.router)
api_v1_router.include_router(pack_sharing.router)
api_v1_router.include_router(providers.router)
api_v1_router.include_router(workflow_packs.router)
api_v1_router.include_router(workflow_runs.router)
