"""cohort_client_brief

Revision ID: 65cf240e087b
Revises: e8b13fa92c4d
Create Date: 2026-08-17 11:49:26.565840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65cf240e087b'
down_revision: Union[str, None] = 'e8b13fa92c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_briefs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('org_id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('client_industry', sa.String(length=100), nullable=True),
    sa.Column('client_website', sa.String(length=500), nullable=True),
    sa.Column('brand_guidelines', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('deliverable_specs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('tone_and_style', sa.Text(), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('budget_range', sa.String(length=100), nullable=True),
    sa.Column('timeline', sa.String(length=200), nullable=True),
    sa.Column('evaluation_criteria', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='brief_status', create_constraint=True), nullable=False),
    sa.Column('created_by', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_briefs_org_status', 'client_briefs', ['org_id', 'status'], unique=False)
    op.create_index('uq_brief_org_slug', 'client_briefs', ['org_id', 'slug'], unique=True)
    op.create_table('cohorts',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('org_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='cohort_status', create_constraint=True), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_learners', sa.Integer(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_by', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cohorts_org_status', 'cohorts', ['org_id', 'status'], unique=False)
    op.create_index('uq_cohort_org_slug', 'cohorts', ['org_id', 'slug'], unique=True)
    op.create_table('brief_applications',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('brief_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('cohort_id', sa.String(length=26), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='application_status', create_constraint=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['brief_id'], ['client_briefs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brief_apps_user', 'brief_applications', ['user_id'], unique=False)
    op.create_index('uq_brief_application', 'brief_applications', ['brief_id', 'user_id'], unique=True)
    op.create_table('cohort_members',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('cohort_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('role', sa.Enum('LEARNER', 'INSTRUCTOR', name='cohort_role', create_constraint=True), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cohort_members_user', 'cohort_members', ['user_id'], unique=False)
    op.create_index('uq_cohort_member', 'cohort_members', ['cohort_id', 'user_id'], unique=True)
    op.create_table('cohort_project_assignments',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('cohort_id', sa.String(length=26), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('deadline_override', sa.DateTime(timezone=True), nullable=True),
    sa.Column('late_deadline_override', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_submissions_override', sa.Integer(), nullable=True),
    sa.Column('participation_mode', sa.Enum('ASSIGNED', 'APPLICATION', name='participation_mode', create_constraint=True), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cohort_projects_project', 'cohort_project_assignments', ['project_id'], unique=False)
    op.create_index('uq_cohort_project', 'cohort_project_assignments', ['cohort_id', 'project_id'], unique=True)
    op.create_table('cohort_skill_assignments',
    sa.Column('cohort_id', sa.String(length=26), nullable=False),
    sa.Column('skill_id', sa.String(length=26), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cohort_id', 'skill_id')
    )
    op.add_column('projects', sa.Column('client_brief_id', sa.String(length=26), nullable=True))
    op.add_column('projects', sa.Column('cohort_id', sa.String(length=26), nullable=True))
    op.create_foreign_key('fk_projects_cohort_id', 'projects', 'cohorts', ['cohort_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_projects_client_brief_id', 'projects', 'client_briefs', ['client_brief_id'], ['id'], ondelete='SET NULL')

    # Extend eval_type enum with new multimodal types
    op.execute("ALTER TYPE eval_type ADD VALUE IF NOT EXISTS 'image_review'")
    op.execute("ALTER TYPE eval_type ADD VALUE IF NOT EXISTS 'video_review'")
    op.execute("ALTER TYPE eval_type ADD VALUE IF NOT EXISTS 'prompt_review'")
    op.execute("ALTER TYPE eval_type ADD VALUE IF NOT EXISTS 'commercial_submission_review'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_projects_client_brief_id', 'projects', type_='foreignkey')
    op.drop_constraint('fk_projects_cohort_id', 'projects', type_='foreignkey')
    op.drop_column('projects', 'cohort_id')
    op.drop_column('projects', 'client_brief_id')
    op.drop_table('cohort_skill_assignments')
    op.drop_index('uq_cohort_project', table_name='cohort_project_assignments')
    op.drop_index('ix_cohort_projects_project', table_name='cohort_project_assignments')
    op.drop_table('cohort_project_assignments')
    op.drop_index('uq_cohort_member', table_name='cohort_members')
    op.drop_index('ix_cohort_members_user', table_name='cohort_members')
    op.drop_table('cohort_members')
    op.drop_index('uq_brief_application', table_name='brief_applications')
    op.drop_index('ix_brief_apps_user', table_name='brief_applications')
    op.drop_table('brief_applications')
    op.drop_index('uq_cohort_org_slug', table_name='cohorts')
    op.drop_index('ix_cohorts_org_status', table_name='cohorts')
    op.drop_table('cohorts')
    op.drop_index('uq_brief_org_slug', table_name='client_briefs')
    op.drop_index('ix_briefs_org_status', table_name='client_briefs')
    op.drop_table('client_briefs')
    # ### end Alembic commands ###
