"""initial schema

Revision ID: 8ecac13ada9e
Revises:
Create Date: 2026-08-13 17:55:11.014179

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8ecac13ada9e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "INSTRUCTOR", "STUDENT", name="user_role", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "SUSPENDED", "DELETED", name="user_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "email_verification_tokens",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "oauth_accounts",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=False),
        sa.Column("provider_email", sa.String(length=255), nullable=True),
        sa.Column("access_token", sa.String(length=1000), nullable=True),
        sa.Column("refresh_token", sa.String(length=1000), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_oauth_provider_id", "oauth_accounts", ["provider", "provider_id"], unique=True
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "SUSPENDED", "ARCHIVED", name="org_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("created_by", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("device_info", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("ix_refresh_tokens_expires", "refresh_tokens", ["expires_at"], unique=False)
    op.create_index(
        "ix_refresh_tokens_user_revoked", "refresh_tokens", ["user_id", "revoked_at"], unique=False
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("username", sa.String(length=40), nullable=False),
        sa.Column("headline", sa.String(length=200), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("website_url", sa.String(length=500), nullable=True),
        sa.Column(
            "social_links",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum("PUBLIC", "PRIVATE", name="profile_visibility", create_constraint=True),
            nullable=False,
        ),
        sa.Column("theme", sa.String(length=20), nullable=False),
        sa.Column("custom_og_image", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index("ix_profiles_username", "user_profiles", ["username"], unique=False)
    op.create_index("ix_profiles_visibility", "user_profiles", ["visibility"], unique=False)
    op.create_table(
        "eval_usage_monthly",
        sa.Column("org_id", sa.String(length=26), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("total_tasks", sa.Integer(), nullable=False),
        sa.Column("total_input_tokens", sa.BigInteger(), nullable=False),
        sa.Column("total_output_tokens", sa.BigInteger(), nullable=False),
        sa.Column("total_cost_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id", "month"),
    )
    op.create_table(
        "org_invitations",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("org_id", sa.String(length=26), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER", "ADMIN", "INSTRUCTOR", "STUDENT", name="org_role", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("invited_by", sa.String(length=26), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "EXPIRED",
                "REVOKED",
                name="invite_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        "ix_org_invitations_email_status", "org_invitations", ["email", "status"], unique=False
    )
    op.create_index(
        "ix_org_invitations_org_status", "org_invitations", ["org_id", "status"], unique=False
    )
    op.create_table(
        "org_invite_links",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("org_id", sa.String(length=26), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER", "ADMIN", "INSTRUCTOR", "STUDENT", name="org_role", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=26), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "org_members",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("org_id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER", "ADMIN", "INSTRUCTOR", "STUDENT", name="org_role", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ARCHIVED", name="member_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("invited_by", sa.String(length=26), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_org_members_org_role", "org_members", ["org_id", "role"], unique=False)
    op.create_index("ix_org_members_user", "org_members", ["user_id"], unique=False)
    op.create_index("uq_org_member", "org_members", ["org_id", "user_id"], unique=True)
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("org_id", sa.String(length=26), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                "EXPERT",
                name="difficulty_level",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("max_score", sa.Integer(), nullable=False),
        sa.Column("rubric", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("late_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("late_penalty_pct", sa.Integer(), nullable=False),
        sa.Column("max_submissions", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "PUBLISHED", "ARCHIVED", name="content_status", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_projects_org_status_deadline",
        "projects",
        ["org_id", "status", "deadline"],
        unique=False,
    )
    op.create_index("uq_project_org_slug", "projects", ["org_id", "slug"], unique=True)
    op.create_table(
        "skill_categories",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("org_id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "PUBLISHED", "ARCHIVED", name="content_status", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("uq_category_org_slug", "skill_categories", ["org_id", "slug"], unique=True)
    op.create_table(
        "project_deliverables",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("project_id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "FILE", "TEXT", "LINK", "MARKDOWN", name="deliverable_type", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_deliverables_project_order",
        "project_deliverables",
        ["project_id", "sort_order"],
        unique=False,
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("org_id", sa.String(length=26), nullable=False),
        sa.Column("category_id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("learning_content", sa.Text(), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                "EXPERT",
                name="difficulty_level",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "PUBLISHED", "ARCHIVED", name="content_status", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["category_id"], ["skill_categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_skills_org_category_order",
        "skills",
        ["org_id", "category_id", "sort_order"],
        unique=False,
    )
    op.create_index("ix_skills_org_status", "skills", ["org_id", "status"], unique=False)
    op.create_index("uq_skill_org_slug", "skills", ["org_id", "slug"], unique=True)
    op.create_table(
        "submission_extensions",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("project_id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("original_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("extended_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("granted_by", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_extension_project_user", "submission_extensions", ["project_id", "user_id"], unique=True
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("org_id", sa.String(length=26), nullable=False),
        sa.Column("project_id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "REVISION_REQUESTED",
                "APPROVED",
                "REJECTED",
                name="submission_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_late", sa.Boolean(), nullable=False),
        sa.Column("final_score", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_submissions_org_status", "submissions", ["org_id", "status"], unique=False)
    op.create_index(
        "ix_submissions_project_user_ver",
        "submissions",
        ["project_id", "user_id", "version"],
        unique=False,
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("org_id", sa.String(length=26), nullable=False),
        sa.Column("skill_id", sa.String(length=26), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "MULTIPLE_CHOICE",
                "TEXT_ANSWER",
                "CODE_SUBMISSION",
                "FILE_UPLOAD",
                name="exercise_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("max_score", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "PUBLISHED", "ARCHIVED", name="content_status", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_exercises_skill_order", "exercises", ["skill_id", "sort_order"], unique=False
    )
    op.create_table(
        "portfolio_items",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("submission_id", sa.String(length=26), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cover_image_url", sa.String(length=500), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("external_url", sa.String(length=500), nullable=True),
        sa.Column("source_org_name", sa.String(length=100), nullable=True),
        sa.Column("source_project", sa.String(length=200), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("show_score", sa.Boolean(), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum(
                "PUBLIC", "UNLISTED", "PRIVATE", name="item_visibility", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("featured", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_portfolio_user_featured", "portfolio_items", ["user_id", "featured"], unique=False
    )
    op.create_index(
        "ix_portfolio_user_vis_order",
        "portfolio_items",
        ["user_id", "visibility", "sort_order"],
        unique=False,
    )
    op.create_index("uq_portfolio_user_slug", "portfolio_items", ["user_id", "slug"], unique=True)
    op.create_table(
        "project_skills",
        sa.Column("project_id", sa.String(length=26), nullable=False),
        sa.Column("skill_id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "skill_id"),
    )
    op.create_table(
        "skill_badges",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("skill_id", sa.String(length=26), nullable=False),
        sa.Column("org_id", sa.String(length=26), nullable=False),
        sa.Column("skill_name", sa.String(length=200), nullable=False),
        sa.Column("category_name", sa.String(length=100), nullable=False),
        sa.Column("completion_pct", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("show_on_profile", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_badges_user_show", "skill_badges", ["user_id", "show_on_profile"], unique=False
    )
    op.create_index(
        "uq_badge_user_skill_org", "skill_badges", ["user_id", "skill_id", "org_id"], unique=True
    )
    op.create_table(
        "skill_prerequisites",
        sa.Column("skill_id", sa.String(length=26), nullable=False),
        sa.Column("prerequisite_id", sa.String(length=26), nullable=False),
        sa.CheckConstraint("skill_id != prerequisite_id", name="ck_no_self_prereq"),
        sa.ForeignKeyConstraint(["prerequisite_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("skill_id", "prerequisite_id"),
    )
    op.create_table(
        "skill_progress",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("org_id", sa.String(length=26), nullable=False),
        sa.Column("skill_id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "IN_PROGRESS",
                "COMPLETED",
                name="progress_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("exercises_total", sa.Integer(), nullable=False),
        sa.Column("exercises_done", sa.Integer(), nullable=False),
        sa.Column("best_score", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_skill_progress_user_org",
        "skill_progress",
        ["user_id", "org_id", "status"],
        unique=False,
    )
    op.create_index("uq_skill_progress", "skill_progress", ["skill_id", "user_id"], unique=True)
    op.create_table(
        "submission_items",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("submission_id", sa.String(length=26), nullable=False),
        sa.Column("deliverable_id", sa.String(length=26), nullable=False),
        sa.Column(
            "type",
            sa.Enum("FILE", "TEXT", "LINK", name="item_type", create_constraint=True),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("file_key", sa.String(length=500), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deliverable_id"], ["project_deliverables.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_submission_items_sub", "submission_items", ["submission_id"], unique=False)
    op.create_table(
        "submission_reviews",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("submission_id", sa.String(length=26), nullable=False),
        sa.Column("reviewer_id", sa.String(length=26), nullable=True),
        sa.Column(
            "reviewer_type",
            sa.Enum("INSTRUCTOR", "AI", name="reviewer_type", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "APPROVED",
                "REVISION_REQUESTED",
                "REJECTED",
                name="review_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("score_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_reviews_sub_created",
        "submission_reviews",
        ["submission_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "exercise_attempts",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("org_id", sa.String(length=26), nullable=False),
        sa.Column("exercise_id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("answer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column(
            "graded_by",
            sa.Enum("AUTO", "MANUAL", "AI", name="grading_method", create_constraint=True),
            nullable=True,
        ),
        sa.Column("graded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_attempts_exercise_user",
        "exercise_attempts",
        ["exercise_id", "user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_attempts_user_org", "exercise_attempts", ["user_id", "org_id"], unique=False
    )
    op.create_table(
        "evaluation_tasks",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("org_id", sa.String(length=26), nullable=False),
        sa.Column("submission_id", sa.String(length=26), nullable=True),
        sa.Column("attempt_id", sa.String(length=26), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "EXERCISE_TEXT",
                "EXERCISE_CODE",
                "SUBMISSION_REVIEW",
                name="eval_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="eval_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("llm_provider", sa.String(length=50), nullable=True),
        sa.Column("llm_model", sa.String(length=100), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["attempt_id"], ["exercise_attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_eval_tasks_org_status", "evaluation_tasks", ["org_id", "status"], unique=False
    )
    op.create_index("ix_eval_tasks_submission", "evaluation_tasks", ["submission_id"], unique=False)
    op.create_index(
        "ix_eval_tasks_worker",
        "evaluation_tasks",
        ["status", "priority", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_eval_tasks_worker", table_name="evaluation_tasks")
    op.drop_index("ix_eval_tasks_submission", table_name="evaluation_tasks")
    op.drop_index("ix_eval_tasks_org_status", table_name="evaluation_tasks")
    op.drop_table("evaluation_tasks")
    op.drop_index("ix_attempts_user_org", table_name="exercise_attempts")
    op.drop_index("ix_attempts_exercise_user", table_name="exercise_attempts")
    op.drop_table("exercise_attempts")
    op.drop_index("ix_reviews_sub_created", table_name="submission_reviews")
    op.drop_table("submission_reviews")
    op.drop_index("ix_submission_items_sub", table_name="submission_items")
    op.drop_table("submission_items")
    op.drop_index("uq_skill_progress", table_name="skill_progress")
    op.drop_index("ix_skill_progress_user_org", table_name="skill_progress")
    op.drop_table("skill_progress")
    op.drop_table("skill_prerequisites")
    op.drop_index("uq_badge_user_skill_org", table_name="skill_badges")
    op.drop_index("ix_badges_user_show", table_name="skill_badges")
    op.drop_table("skill_badges")
    op.drop_table("project_skills")
    op.drop_index("uq_portfolio_user_slug", table_name="portfolio_items")
    op.drop_index("ix_portfolio_user_vis_order", table_name="portfolio_items")
    op.drop_index("ix_portfolio_user_featured", table_name="portfolio_items")
    op.drop_table("portfolio_items")
    op.drop_index("ix_exercises_skill_order", table_name="exercises")
    op.drop_table("exercises")
    op.drop_index("ix_submissions_project_user_ver", table_name="submissions")
    op.drop_index("ix_submissions_org_status", table_name="submissions")
    op.drop_table("submissions")
    op.drop_index("uq_extension_project_user", table_name="submission_extensions")
    op.drop_table("submission_extensions")
    op.drop_index("uq_skill_org_slug", table_name="skills")
    op.drop_index("ix_skills_org_status", table_name="skills")
    op.drop_index("ix_skills_org_category_order", table_name="skills")
    op.drop_table("skills")
    op.drop_index("ix_deliverables_project_order", table_name="project_deliverables")
    op.drop_table("project_deliverables")
    op.drop_index("uq_category_org_slug", table_name="skill_categories")
    op.drop_table("skill_categories")
    op.drop_index("uq_project_org_slug", table_name="projects")
    op.drop_index("ix_projects_org_status_deadline", table_name="projects")
    op.drop_table("projects")
    op.drop_index("uq_org_member", table_name="org_members")
    op.drop_index("ix_org_members_user", table_name="org_members")
    op.drop_index("ix_org_members_org_role", table_name="org_members")
    op.drop_table("org_members")
    op.drop_table("org_invite_links")
    op.drop_index("ix_org_invitations_org_status", table_name="org_invitations")
    op.drop_index("ix_org_invitations_email_status", table_name="org_invitations")
    op.drop_table("org_invitations")
    op.drop_table("eval_usage_monthly")
    op.drop_index("ix_profiles_visibility", table_name="user_profiles")
    op.drop_index("ix_profiles_username", table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index("ix_refresh_tokens_user_revoked", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_expires", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_table("organizations")
    op.drop_index("uq_oauth_provider_id", table_name="oauth_accounts")
    op.drop_table("oauth_accounts")
    op.drop_table("email_verification_tokens")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
