"""project_creator_assignment

Revision ID: af18bccf7908
Revises: 65cf240e087b
Create Date: 2026-08-17 15:10:34.449920

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af18bccf7908"
down_revision: str | None = "65cf240e087b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_creator_assignments",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("project_id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("assigned_by", sa.String(length=26), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_project_creators_user", "project_creator_assignments", ["user_id"], unique=False
    )
    op.create_index(
        "uq_project_creator", "project_creator_assignments", ["project_id", "user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_project_creator", table_name="project_creator_assignments")
    op.drop_index("ix_project_creators_user", table_name="project_creator_assignments")
    op.drop_table("project_creator_assignments")
    # ### end Alembic commands ###
